//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int id { get; set; }
        public string NameBook { get; set; }
        public string Name { get; set; }
        public string Topic { get; set; }
        public string TypeExchange { get; set; }
    }
}
